(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s2=function(a){a.V("cardstatechange",g.CT(a)&&g.DT(a)?1:0)},NDa=function(a){var b=g.vg(a);
a=g.Bg(a);return new g.ag(b.x,b.y,a.width,a.height)},ODa=function(a){return Math.pow(a,3)},PDa=function(a){return 3*a*a-2*a*a*a},v2=function(a){a=g.Qa(a);
delete t2[a];g.Sb(t2)&&u2&&u2.stop()},RDa=function(){u2||(u2=new g.F(function(){QDa()},20));
var a=u2;a.isActive()||a.start()},QDa=function(){var a=g.A();
g.Eb(t2,function(b){SDa(b,a)});
g.Sb(t2)||RDa()},w2=function(a,b,c,d){g.hn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.I=0;this.D=null},SDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.D);a.D=b;TDa(a,a.progress);1==a.progress?(a.Ia=0,v2(a),a.Rf(),a.Tp()):a.Jb()&&a.yw()},TDa=function(a,b){"function"===typeof a.F&&(b=a.F(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},UDa=function(a,b){g.ql.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Ia},x2=function(a,b,c,d,e){w2.call(this,b,c,d,e);
this.element=a},y2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
x2.call(this,a,b,c,d,e)},z2=function(a){g.C.call(this);
this.B=a||window;this.u=[]},A2=function(a){return a.baseUrl||null},B2=function(a,b){return g.Fe(g.Lc(a,b,void 0),function(c){return!!c})},VDa=function(a,b,c){function d(jb){var eb,Xa,$d,Xc=jb.hovercardButton;
if(!Xc)return null;Xc=Xc.subscribeButtonRenderer;if(!Xc)return null;var Gi=f(Xc.unsubscribedButtonText),Hi=f(Xc.subscribedButtonText);if(Xc.subscribed){var Ch=f(Xc.subscriberCountWithUnsubscribeText);var Ii=f(Xc.subscriberCountText)}else Ch=f(Xc.subscriberCountText),Ii=f(Xc.subscriberCountWithSubscribeText);var nf=null;return jb.signinEndpoint&&(nf=g.Nb(jb,"signinEndpoint","webNavigationEndpointData","url"),nf||(nf=null===($d=null===(Xa=null===(eb=Xc.signInEndpoint)||void 0===eb?void 0:eb.commandMetadata)||
void 0===Xa?void 0:Xa.webCommandMetadata)||void 0===$d?void 0:$d.url),!nf)?null:Gi&&(Hi||nf)?{subscribed:Xc.subscribed,subscribeText:Gi,subscribeCount:Ch,unsubscribeText:Hi,unsubscribeCount:Ii,enabled:Xc.enabled,signinUrl:nf,classic:jb.useClassicSubscribeButton}:null}
function e(jb){if(jb){var eb=[],Xa=jb.videoId;Xa&&eb.push("v="+Xa);(Xa=jb.playlistId)&&eb.push("list="+Xa);(jb=jb.startTimeSeconds)&&eb.push("t="+jb);return"/watch?"+eb.join("&")}}
function f(jb){if(!jb)return null;var eb=jb.simpleText;return eb?eb:jb.runs?g.Lc(jb.runs,function(Xa){return Xa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,B=null,E=null,G=null,J=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=g.Nb(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((E=g.Nb(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(J=f(b.additionalFeesText)),(n=g.Nb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Nb(b,"title","accessibility","accessibilityData","label");var I=b.endpoint?b.endpoint.clickTrackingParams:null,Ca="";if(b.metadata){var ta=f(b.metadata);ta&&(Ca=ta)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Ca,callToAction:f(b.callToAction),
TA:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,qJ:n,md:I?{itct:I}:null,wQ:p,xo:a?a:null,tJ:b.isPlaceholder,impressionUrls:B2(b.impressionUrls||[],A2),iJ:B2(b.hovercardShowUrls||[],A2),clickUrls:B2(l.loggingUrls||[],A2),visualElement:g.Ys(b.trackingParams),
productPrice:G,additionalFeesText:J}},C2=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:B2(a.impressionUrls||[],A2),elements:B2(a.elements||[],function(d,e){return VDa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Ys(a.trackingParams));return c},D2=function(a){g.sS.call(this,a);
this.C=this.endscreen=null;this.u={};this.F={};this.D=this.B=null;this.K=[];this.P=!0;this.I=0;a=a.T();this.N=g.UC(a)||g.WC(a);this.events=new g.cR(this);g.D(this,this.events);this.events.R(this.player,g.bE("creatorendscreen"),this.dK);this.events.R(this.player,g.cE("creatorendscreen"),this.eK);this.events.R(this.player,"resize",this.Ta);this.events.R(window,"focus",this.uP);this.load();var b=g.Ae("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Wf(this,function(){g.Ee(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},WDa=function(a){return a.player.getVideoData().jc?"current":a.N?"new":"current"},E2=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},XDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",Rf:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=C2(f,WDa(a))));F2(a,f)},
Wh:{v:c},withCredentials:!0};a.N&&(c.Wh.ptype="embedded");var d=b.Jr;d&&(c.oc={ad_tracking:d});if(b=g.vH(b))if(b=g.Gc(b),b=g.Cc(b))a.C=g.Vp(b,c)},F2=function(a,b,c){c=void 0===c?!0:c;
g.GT(a.player,"creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.q(Object.values(a.u)),e=d.next();!e.done;e=d.next())e.value.dispose();a.u={};a.F={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&YDa(a);c=[];d=new g.ZD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().u||(a.B=new g.V({G:"div",L:"ytp-ce-shadow"}),g.iP(a.player,a.B.element,4),a.D=new g.TN(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=ZDa(a,e);if(f){a.u[e.id]=f;a.F[e.id]=e;g.iP(a.player,f.element,4);var h=new g.ZD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);$Da(a,f,e)}else g.Ur(new g.Gq("buildEndscreenElement null",
e))}g.eN(a.player,c);a.Ta()}},YDa=function(a){var b=g.bt(),c=g.dt();
c&&b&&a.endscreen.visualElement&&g.qt(c,b,a.endscreen.visualElement)},ZDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.aa("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",ia:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",U:G2(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",U:{href:H2(a,b.targetUrl),tabindex:"-1"},S:[{G:"div",ia:["ytp-ce-video-title"].concat(g.la(c)),U:{dir:g.on(b.title||
"")},Z:b.title},{G:"div",L:"ytp-ce-video-duration",Z:b.videoDuration||void 0}]}]};c=new g.V(c);break;case "PLAYLIST":c=a.player.aa("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",ia:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",U:G2(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",U:{href:H2(a,
b.targetUrl),tabindex:"-1"},S:[{G:"div",ia:["ytp-ce-playlist-title"].concat(g.la(c)),U:{dir:g.on(b.title||"")},Z:b.title},{G:"div",L:"ytp-ce-playlist-count",S:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.V(c);break;case "CHANNEL":c={G:"div",ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"a",ia:["ytp-ce-channel-title","ytp-ce-link"],U:{href:H2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.on(b.title||"")},Z:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",S:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{G:"div",ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",U:G2(b)}]};c=new g.V(c);var d=g.ke(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.H(d,"ytp-ce-subscribe-button");if(a.player.T().u){var e=null;var f=b.md.itct}else e="endscreen",f=null;e=new g.XU(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":c={G:"div",ia:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"div",L:"ytp-ce-website-title",U:{dir:g.on(b.title||"")},Z:b.title},{G:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{G:"a",ia:["ytp-ce-website-goto","ytp-ce-link"],U:{href:H2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",U:G2(b)},{G:"div",
L:"ytp-ce-expanding-icon",U:aEa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",S:[{G:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.S.push({G:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),c={G:"div",ia:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},S:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
S:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",S:[{G:"div",L:"ytp-ce-expanding-overlay-body",S:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{G:"div",L:"ytp-ce-merchandise-title",U:{dir:g.on(b.title||"")},Z:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{G:"a",ia:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:H2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",U:G2(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",S:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.V(c)}b.tJ&&g.H(c.element,"ytp-ce-placeholder");return c},G2=function(a){if(a.TA)var b=a.TA.thumbnails;
return aEa(b?b[b.length-1].url:null)},aEa=function(a){return a?{style:"background-image: url("+a+")"}:{}},$Da=function(a,b,c){function d(m){m&&(b.wa("blur",function(){"none"!=m.style.display&&a.P&&m.focus()}),b.R(m,"focus",f),b.R(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.H(b.element,"ytp-ce-force-expand"),I2(a,c.id,!0)):(g.en(b.element,"ytp-ce-force-expand"),g.en(b.element,"ytp-ce-element-hover"),I2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.wa("mouseenter",function(){J2(a,b,c)});
b.wa("mouseleave",function(){K2(a,b,c)});
a.player.T().u||b.wa("click",function(){g.H(b.element,"ytp-ce-element-hover")});
b.wa("click",function(m){bEa(a,c,m)});
b.wa("keypress",function(m){bEa(a,c,m)});
b.wa("focus",function(){J2(a,b,c)});
b.wa("blur",function(){K2(a,b,c)});
b.wa("touchstart",function(){J2(a,b,c)});
var l=g.me("ytp-ce-expanding-overlay-hider",b.element);l&&b.R(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.en(b.element,"ytp-ce-element-hover");g.en(b.element,"ytp-ce-force-expand")});
b.wa("keydown",function(m){a.P=9===m.keyCode&&!m.shiftKey});
d(g.me("ytp-sb-subscribe",b.element));d(g.me("ytp-sb-unsubscribe",b.element));b.wa("focus",f);b.wa("blur",h)},bEa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.cn(d,"ytp-ce-element");){g.cn(d,"subscribe-label")&&L2(a,b);
if(g.cn(d,"ytp-ce-channel-subscribe"))return;d=g.Ge(d)}if(!d||g.cn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.u[b.id])K2(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.wQ)L2(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Gc(H2(a,b.targetUrl)),c=g.Cc(c),g.TK(c,void 0,b.md);else{var e=a.player.getVideoData().jc,f=function(){var h=H2(a,b.targetUrl),l=b.md,m=g.Dp(h);e&&m&&(m.v||m.list)?g.qT(a.player,m.v,l,m.list,!1):g.SK(h,l)};
L2(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},H2=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.zD(c)+b}else return"";return b},J2=function(a,b,c){g.cn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.H(b.element,"ytp-ce-element-hover"):a.player.T().u?(new g.F(function(){g.H(b.element,"ytp-ce-element-hover")},200)).start():g.H(b.element,"ytp-ce-element-hover"),M2(a,c.iJ),I2(a,c.id,!0))},K2=function(a,b,c){g.en(b.element,"ytp-ce-element-hover");
g.en(b.element,"ytp-ce-force-expand");I2(a,c.id,!1)},I2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.q(Object.keys(a.u)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.K(a.u[e].element,"ytp-ce-element-shadow-show",c)},M2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||E2(a))c&&c();else{b=cEa(a,b);var e=0,f=!1,h=new g.F(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Et(b[a],d)}},L2=function(a,b,c){M2(a,b.clickUrls,c);
(a=g.dt())&&b.qJ&&g.ut(a,b.visualElement)},cEa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(dEa(b[e],c));return d},dEa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},eEa=function(a){return Array.isArray(a)&&a.length?a[0]:a},N2=function(a){return"string"===typeof a?a:""},O2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},fEa=function(a){this.externalId=a},gEa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.u=d},P2=function(a){return a.value?a.value:null},Q2=function(a){if(!a)return null;
var b=g.Gc(N2(a.value));b=g.Cc(b);if(!b)return null;var c=O2(a.target,hEa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new gEa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},iEa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},lEa=function(a){if(!a)return null;
var b=O2(a.type,jEa),c=O2(a.trigger,kEa),d=eEa(a.url);d=Q2(d?d:null);a=eEa(a.subscribeData);var e=a?a:null;e?(a=N2(e.external_user_id),e=N2(e.subscription_token),a=a&&e?new fEa(a):null):a=null;return b?new iEa(b,c,d,a):null},R2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},mEa=function(a,b){return g.db(a.action,b,void 0)},nEa=function(a,b){this.context=a;
this.u=b},T2=function(a){return a.customMessage?S2("div","iv-card-message",a.customMessage):""},U2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{G:"div",L:"iv-card-image",U:{style:c},S:d}},V2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S2("li","",c.value));return{G:"ul",L:"iv-card-meta-info",S:b}},S2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.on(c);return{G:a,U:b,Z:c}},oEa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.rr&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.rr+");");c.dir=g.on(a.customMessage);var d=[{G:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",ia:b,U:c,S:d}},W2=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.u(e.value,d,c.id,c.md,c.Jf.click,5)}},pEa=function(a,b){this.merchant=a;
this.price=b},qEa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},rEa=function(a,b){return b?b:qEa(a)?"current":"new"},X2=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.Ha=!1;this.va=new Map;this.Ca=new Map;this.context.J.addEventListener(g.bE("annotations_module"),function(d){(d=c.va.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.cE("annotations_module"),function(d){(d=c.Ca.get(d))&&d.apply(c)})},Y2=function(a,b,c,d,e,f,h){a.context.u.wa(b,"click",function(l){a.zx(c,d,e,f||[],h||0,l)});
a.context.u.wa(b,"touchstart",function(){a.Ha=!1});
a.context.u.wa(b,"touchmove",function(){a.Ha=!0})},sEa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z2=function(a,b,c){return{VB:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
UF:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Au:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b3=function(a,b,c){X2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.ea=this.Xa=this.C=this.Pd=!1;this.ka=null;this.cards=[];this.Qa=this.N=this.fa=this.F=this.la=this.u=null;this.W=[];this.K=this.Cd=this.ca=null;this.I=0;this.Y=new g.F(g.Ka,c.D.Hd?4E3:3E3);g.D(this,this.Y);this.Pa=new g.F(g.Ka);g.D(this,this.Pa);this.X=new nEa(c,function(e,f,h,l,m,n){Y2(d,e,f,h,l,m,n)});
this.P=new g.V({G:"div",L:"iv-drawer",U:{id:"iv-drawer"},S:[{G:"div",L:"iv-drawer-header",U:{"aria-role":"heading"},S:[{G:"span",L:"iv-drawer-header-text"},{G:"button",ia:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.D(this,this.P);this.D=this.P.element;this.Aa=new g.TN(this.P,330);g.D(this,this.Aa);this.Va=g.me("iv-drawer-header-text",this.D);this.B=g.me("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Xa&&$2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Xa=d.C)&&a3(d)})},tEa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){$2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){a3(a)});
var d=c.headerText;g.Ie(a.Va,d);a.N&&a.N.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.ca=g.Ys(c.trackingParams);a.K=g.Ys(c.closeTrackingParams);a.Cd=g.Ys(c.iconTrackingParams)},uEa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,md:c3(a,c,b,d),sponsored:!1,Jf:Z2(d,e,d.command),hj:d.trackingParams?g.Ys(d.trackingParams):null,Vg:e.trackingParams?g.Ys(e.trackingParams):
null,Cd:f&&f.trackingParams?g.Ys(f.trackingParams):null,imageUrl:d3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.T(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,rr:null,title:d.title?g.T(d.title):"",customMessage:d.callToAction?g.T(d.callToAction):"",url:d.command.urlEndpoint.url?Q2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,md:c3(a,c,b,d),sponsored:!1,Jf:Z2(d,e,d.endpoint),hj:d.trackingParams?g.Ys(d.trackingParams):null,Vg:e.trackingParams?g.Ys(e.trackingParams):null,Cd:f&&f.trackingParams?g.Ys(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.T(d.customText):null,VE:d3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.T(d.channelName):"",metaInfo:[d.subscriberCountText?g.T(d.subscriberCountText):""],url:Q2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};e3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,md:c3(a,c,b,d),sponsored:!1,Jf:Z2(d,e,d.action),hj:d.trackingParams?g.Ys(d.trackingParams):null,Vg:e.trackingParams?g.Ys(e.trackingParams):null,Cd:f&&f.trackingParams?g.Ys(f.trackingParams):
null,Eq:d3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.T(d.customMessage):null,playlistVideoCount:g.T(d.playlistVideoCount),title:d.playlistTitle?g.T(d.playlistTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.videoCountText?g.T(d.videoCountText):""],url:Q2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:sEa(d.action)})};e3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.T(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,md:c3(a,c,b,d),sponsored:!1,Jf:Z2(d,e,d.action),hj:d.trackingParams?g.Ys(d.trackingParams):null,Vg:e.trackingParams?g.Ys(e.trackingParams):null,Cd:f&&f.trackingParams?g.Ys(f.trackingParams):null,Eq:d3(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.T(d.lengthString):null,customMessage:d.customMessage?g.T(d.customMessage):null,title:d.videoTitle?g.T(d.videoTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.viewCountText?g.T(d.viewCountText):""],isLiveNow:!!d.badge,url:Q2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:sEa(d.action)})};e3(a,c)}a.I++},d3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},wEa=function(a,b){var c=vEa(a,b);
c&&(c===a.u&&(a.u=null),a.J.removeCueRange(c.card.id),g.Ee(c.Cv),g.ob(a.cards,c),a.tr(),f3(a))},$2=function(a,b,c){if(!a.C){a.Aa.show();
a.la=new g.F(function(){g.H(a.context.J.getRootNode(),g.WY.IV_DRAWER_OPEN)},0);
a.la.start();a.ka=g.Ho(a.B,"mousewheel",function(h){a.Y.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.dt();d&&a.ca&&a.K&&g.rt(d,[a.ca,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.BC||(f.BC=!0,xEa(a.context.logger,f.card.Jf.VB,b)),d&&g.rt(d,[f.card.hj]);s2(a.J);c&&(a.F=new g.F(function(){a.fa=a.N;a.Qa.focus()},330),a.F.start())}},a3=function(a){a.C&&(a.Aa.hide(),g.Io(a.ka),a.ka=null,g.en(a.context.J.getRootNode(),g.WY.IV_DRAWER_OPEN),a.C=!1,s2(a.J),a.F&&a.F.stop(),a.F=new g.F(function(){a.fa&&(a.fa.focus(),a.fa=null)},330),a.F.start())},zEa=
function(a){g.dn(a.Na(),[g.WY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.iP(a.J,a.D,5);yEa(a);a.N=g.me("ytp-cards-button",a.J.getRootNode());a.Qa=g.me("iv-drawer-close-button",a.D);a.Pd=!0},yEa=function(a){var b=g.me("iv-drawer-close-button",a.D);
a.context.u.wa(b,"click",a.LH,a);a.context.u.wa(a.B,"touchend",function(){a.Y.start()});
a.context.u.wa(a.B,"scroll",a.aI,a);a.context.B.subscribe("onHideControls",function(){a.ea=!0});
a.context.B.subscribe("onShowControls",function(){a.ea=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.ea=g.cn(a.J.getRootNode(),"ytp-autohide")});
a.W.push(g.ro("iv-button-shown",a.xJ,a));a.W.push(g.ro("iv-button-hidden",a.wJ,a));a.W.push(g.ro("iv-teaser-shown",a.yK,a));a.W.push(g.ro("iv-teaser-hidden",a.zJ,a));a.W.push(g.ro("iv-teaser-clicked",a.xK,a))},e3=function(a,b){a.Pd||zEa(a);
wEa(a,b.id);var c=AEa(a,b);if(c){var d={card:b,Cv:c.element,BC:!1},e=BEa(a,d);g.ub(a.cards,e,0,d);c.ga(a.B,e);a.tr();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.u=d,f3(a),CEa(a,d),$2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&DEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){DEa(a,d)}),f3(a))}},AEa=function(a,b){switch(b.type){case "simple":var c=a.X;
var d=b.displayDomain?{G:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var e=oEa(b);d={G:"div",ia:["iv-card"],S:[{G:"a",L:"iv-click-target",U:{href:b.url?P2(b.url)||"":""},S:[U2(b.imageUrl,d),{G:"div",L:"iv-card-content",S:[S2("h2",void 0,b.title),e]}]}]};d=new g.V(d);W2(c,g.le("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.X,d={G:"div",ia:["iv-card","iv-card-channel"],S:[{G:"a",ia:["iv-click-target"],U:{href:P2(b.url)||"","data-ytid":b.channelId},S:[U2(b.VE),
{G:"div",L:"iv-card-content",S:[T2(b),{G:"h2",L:"iv-card-primary-link",Z:b.title},V2(b)]}]}]},d=new g.V(d),W2(c,g.le("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.X,d={G:"div",ia:["iv-card","iv-card-playlist"],S:[{G:"a",L:"iv-click-target",U:{href:P2(b.url)||""},S:[U2(b.Eq,{G:"div",L:"iv-card-image-overlay",S:[{G:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",S:[T2(b),S2("h2","iv-card-primary-link",b.title),V2(b)]}]}]},d=new g.V(d),
W2(c,g.le("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.X;var f=!g.kb(b.offers);d=["iv-card"];e="";var h=oEa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",L:"iv-card-offer-price",Z:h.price}),h.merchant&&f.push({G:"div",L:"iv-card-offer-merchant",Z:h.merchant}),h={G:"div",S:f});f=b.url?P2(b.url)||"":"";d={G:"div",ia:d,U:{tabindex:"0"},S:[{G:"a",ia:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",S:[b.sponsored?{G:"div",L:"iv-card-sponsored",S:["Sponsored",{G:"div",L:"iv-ad-info-container",S:[{G:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",S:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",U:{href:f},S:[S2("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.Ae("span");g.Ie(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.zc(e,"adInfo");W2(c,g.le("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.X,d=b.isLiveNow?{G:"span",ia:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,d={G:"div",ia:["iv-card","iv-card-video"],S:[{G:"a",L:"iv-click-target",U:{href:P2(b.url)||""},S:[U2(b.Eq,b.videoDuration?{G:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0),{G:"div",L:"iv-card-content",S:[T2(b),S2("h2","iv-card-primary-link",b.title),V2(b),d]}]}]},d=new g.V(d),W2(c,g.le("iv-click-target",d.element),
b,b.url),d;default:return null}},BEa=function(a,b){if(0===a.cards.length)return 0;
var c=g.fb(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},EEa=function(a){return a.u?"productListing"===a.u.card.type:g.gh(a.cards,function(b){return"productListing"===b.card.type})},f3=function(a){g.K(a.J.getRootNode(),"ytp-cards-shopping-active",EEa(a))},DEa=function(a,b){if(!g.cn(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.u!==b){var c=g.dt(),d=a.u?a.u.card.Cd:a.Cd;
c&&d&&g.tt(c,[d]);a.u=b;f3(a)}if(c="none"!=a.Na().style.display)2===a.context.J.getPresentingPlayerType()?c=1===a.context.J.getAdState():(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.BT(g.rT(a.J)))&&d.tx(!0,c));a.Pa.isActive()||((!a.C||!a.Y.isActive()&&a.ea)&&CEa(a,b),a.Pa.start(910+b.card.teaserDurationMs))}},CEa=function(a,b){if(a.P.ab){var c=new w2([0,
a.B.scrollTop],[0,b.Cv.offsetTop],600,PDa);a.context.C.wa(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.C.wa(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.pN(a.P,!0),a.B.scrollTop=b.Cv.offsetTop,g.pN(a.P,!1)},g3=function(a){return a.u&&a.u.card?a.u.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},vEa=function(a,b){return g.db(a.cards,function(c){return c.card.id===b})},h3=function(a,b,c){X2.call(this,a,b);
this.annotation=c;this.isActive=!1},FEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i3=function(a,b,c){h3.call(this,a,b,c);
this.B=null;this.K=!1;this.C=null;this.D=!1;this.u=this.I=this.F=null},GEa=function(a,b){var c=void 0===c?0:c;
var d=NDa(b).width;g.tg(b,d);c=new y2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,ODa);g.D(a,c);a.context.C.wa(c,"begin",function(){g.Cg(b,!0)});
c.play()},JEa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
ia:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({G:"div",ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.u=new g.XU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.J),a.u.ga(d));var f=a.createElement({G:"div",ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Cg(h,!1);var l=a.createElement({G:"div",ia:["branding-context-container-outer"]});l.appendChild(h);g.lg(l,"right",b.image_width+"px");a.Na().appendChild(l);a.C=new g.F(function(){HEa(a,h,l)},500);
g.D(a,a.C);a.context.u.wa(a.Na(),"mouseover",function(){IEa(a,h,l,f,b.image_height)});
a.context.u.wa(a.Na(),"mouseout",function(){a.C.start()})}},IEa=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Bg(b);a.u||(b.style.width=g.sg(f.width,!0),c.style.width=g.sg(f.width,!0));g.lg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.lg(d,"right","1px");a.D=!0;g.Cg(b,!0);a.F=new g.F(function(){g.H(this.Na(),"iv-branding-active")},0,a);
a.F.start()}},HEa=function(a,b,c){g.en(a.Na(),"iv-branding-active");
a.I=new g.F(function(){g.Cg(b,!1);a.u||(c.style.width=g.sg(0,!0))},250);
a.I.start();a.D=!1},KEa=function(a,b,c,d,e,f,h){this.u=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},j3=function(a,b,c){h3.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.P=!1;this.I=5E3;this.B=this.C=this.u=this.D=null;this.K=this.createElement({G:"div",ia:["iv-promo-contents"]});this.F=new g.F(function(){d.u.setAttribute("aria-hidden","true");g.Cg(d.C,!1);g.Cg(d.B,!0)},700,this);
g.D(this,this.F)},LEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.Na().setAttribute("aria-hidden","true");a.Na().setAttribute("aria-label","Promotion");a.Na().tabIndex=0;var e=a.annotation.Bd(),f=b.image_url;if(f){var h=a.createElement({G:"div",ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&Y2(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.ed(f,P2(e)),a.u=f):a.u=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",S:[{G:"strong",Z:b.text_line_1}]});
var m=a.createElement({G:"p",S:[{G:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",ia:["iv-button","iv-promo-button"],S:[{G:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y2(a,a.Na(),e,a.annotation.id,b.session_data,void 0,c)}g.H(a.u,"iv-click-target");
e&&Y2(a,a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",S:[{G:"span",Z:b.text_line_1}]}),m=a.createElement({G:"p",S:[{G:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",ia:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.H(a.u,"iv-click-target"),e&&Y2(a,a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.K.appendChild(a.u);p&&a.K.appendChild(p);c=
a.createElement({G:"div",L:"iv-promo-actions"});a.B=a.createElement({G:"button",ia:["iv-promo-expand","ytp-button"]});a.B.title="Expand";a.context.u.wa(a.B,"click",function(r){k3(a,5E3,r)});
c.appendChild(a.B);g.Cg(a.B,!1);a.context.u.wa(a.Na(),"mouseover",a.QI,a);a.context.u.wa(a.Na(),"mouseout",a.OI,a);a.context.u.wa(a.Na(),"touchend",function(r){k3(a,5E3,r)});
a.C=a.createElement({G:"button",ia:["iv-promo-close","ytp-button"]});a.C.title="Close";a.context.u.wa(a.C,"click","cta"===a.annotation.style&&b.text_line_3?a.JI:a.II,a);c.appendChild(a.C);g.dn(a.Na(),d);h&&(a.Na().appendChild(h),n&&h.appendChild(n));a.Na().appendChild(a.K);a.Na().appendChild(c)},k3=function(a,b,c){c.stopPropagation();
MEa(a);NEa(a,b);a.u.focus()},OEa=function(a){a.isCollapsed||a.N||a.D||(g.H(a.Na(),"iv-promo-collapsed"),a.isCollapsed=!0,a.F.start())},MEa=function(a){a.F.stop();
a.isCollapsed&&(g.fn(a.Na(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Cg(a.B,!1),g.Cg(a.C,!0))},NEa=function(a,b){a.D||(a.D=g.ym(function(){l3(this);
OEa(this)},b,a))},l3=function(a){a.D&&(g.v.clearTimeout(a.D),a.D=null)},PEa=function(a){this.J=a},xEa=function(a,b,c){b&&(c?m3(a,b.map(function(d){return g.Sm(d,c)})):m3(a,b))},m3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Et(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},n3=function(a){g.sS.call(this,a);
var b=this;this.P=!1;this.loadNumber=0;this.K={};this.logger=new PEa(this.player);this.F=new g.cR(this);this.I=this.C=null;this.events=new g.cR(this);this.N=this.u=null;this.W=[];g.D(this,this.F);this.F.R(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.F.R(this.player,"onHideControls",function(){b.V("onHideControls")});
this.F.R(this.player,"onShowControls",function(){b.V("onShowControls")});
this.F.R(this.player,"resize",function(d){b.V("resize",d)});
this.F.R(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.wK,this);this.subscribe("resize",this.Ut,this);this.player.T().K.subscribe("vast_info_card_add",this.DE,this);g.D(this,this.events);this.X=this.createElement({G:"div",L:"video-custom-annotations"});this.B=new g.V({G:"div",ia:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.B);g.iP(this.player,this.B.element,4);this.B.hide();this.D=new g.V({G:"div",ia:["ytp-iv-video-content"]});g.D(this,this.D);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.X);this.D.element.appendChild(a);QEa(this)&&this.load();var c=this.createElement({G:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Wf(this,function(){g.Ee(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},REa=function(a){a=a.createElement({G:"div",
ia:["annotation","annotation-type-custom"]});g.Cg(a,!1);return a},QEa=function(a){var b=a.player.T();
a=a.player.getVideoData();return a.jc&&b.pfpChazalUi?!1:1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.zG||b.K.get(a.videoId)||g.xH(a)||g.yH(a)?!0:!1},SEa=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.pN(a.B,c);g.pN(a.D,c)},TEa=function(a,b,c){a.P=!0;
a.I=g.Vp(b,c)},UEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(UEa(a,e))}return c},XEa=function(a){var b=a.player.getVideoData();
if(b.Bg){var c=a.player.T().K.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Pp(h)&&h.responseXML?h.responseXML:null)&&o3(a,h)}};
g.Zo()&&(d.onFinish=VEa(a,d.onFinish));d.postParams={ic_only:"1"};WEa(d,c);a.P=!0;g.Vp(b.Bg,d)}}},WEa=function(a,b){a.method="POST";
a.oc=a.oc||{};b.Ho&&(a.oc.ic_coll=b.Ho);b.xr&&(a.oc.ic_xml=b.xr);b.Iq&&(a.oc.ic_track=b.Iq)},YEa=function(a){var b=new g.V({G:"div"});
g.Cg(b.element,!1);var c=new b3(a.player,b.element,p3(a));g.D(c,b);b.ga(a.B.element);c.rq();return c},p3=function(a){if(!a.N){var b=new z2(a);
g.D(a,b);var c=new g.g1(a);g.D(a,c);a.N=new KEa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Pa)}return a.N},o3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.dt();if(e){var f=g.bt();f&&g.jt(g.Zn("use_default_events_client")?void 0:g.Or,e,f,[g.Ys(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=UEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=O2(h.type,ZEa),r=O2(h.style,$Ea),t=N2(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=lEa;if(null==x)var y=null;else if(g.Na(x)){m=[];for(var B=g.q(x),E=B.next();!E.done;E=
B.next()){var G=h(E.value);G&&m.push(G)}y=m}else{var J=h(x);y=J?[J]:[]}f=n&&p?new R2(n,p,r,y,w):null}else f=null}catch(Xa){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var I=REa(h),Ca=null;switch(m.type){case "branding":if(h.player.T().jb)break;h.B.element.appendChild(I);Ca=new i3(I,p3(h),m);break;case "promotion":g.iP(h.player,I,4),Ca=new j3(I,p3(h),m)}Ca&&Ca.rq();if(h=Ca)g.D(a,h),a.K[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.u||(a.u=YEa(a),g.D(a,a.u));if("card"===f.type){c=
a.u;var ta=f&&f.data&&f.data.card_type;h=f.data;if(ta)switch(m=h.tracking||{},m={VB:m.impression,click:m.click,close:m.close,UF:m.teaser_impression,Au:m.teaser_click},I=h.tracking_params||{},Ca=null,ta){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,md:h.session_data||{},sponsored:h.sponsored||!1,Jf:m,hj:I.card?g.Ys(I.card):null,Vg:I.teaser?g.Ys(I.teaser):null,Cd:I.icon?
g.Ys(I.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,VE:h.image_url,title:h.title,metaInfo:h.meta_info,url:Q2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};e3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,md:h.session_data||{},sponsored:h.sponsored||!1,Jf:m,hj:I.card?g.Ys(I.card):null,
Vg:I.teaser?g.Ys(I.teaser):null,Cd:I.icon?g.Ys(I.icon):null,Eq:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:Q2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};e3(c,f);break;case "productListing":h.signin_url&&(Ca=Q2({target:"current",value:h.signin_url}));ta=[];for(var jb=h.offers||[],eb=0;eb<jb.length;eb++)ta.push(new pEa(g.kd(jb[eb].merchant),g.kd(jb[eb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,md:h.session_data||{},sponsored:h.sponsored||!1,Jf:m,hj:I.card?g.Ys(I.card):null,Vg:I.teaser?g.Ys(I.teaser):null,Cd:I.icon?g.Ys(I.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,rr:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:Q2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),D3:Ca,C3:h.signin_title?h.signin_title:void 0,B3:h.signin_message?h.signin_message:void 0,offers:ta};e3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,md:h.session_data||{},sponsored:h.sponsored||!1,Jf:m,hj:I.card?g.Ys(I.card):null,Vg:I.teaser?g.Ys(I.teaser):null,Cd:I.icon?
g.Ys(I.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,rr:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:Q2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};e3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,md:h.session_data||{},sponsored:h.sponsored||!1,Jf:m,hj:I.card?g.Ys(I.card):null,Vg:I.teaser?g.Ys(I.teaser):null,Cd:I.icon?g.Ys(I.icon):null,Eq:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:Q2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},e3(c,f)}}else tEa(a.u,f);c=!0}}c&&(s2(a.player),a.Ut())},aFa=function(a,b){var c=!1;
a.u||(a.u=YEa(a),g.D(a,a.u));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(uEa(a.u,e.cardRenderer),c=!0);c&&(c=a.u,d=b.headerText?g.T(b.headerText):"",g.Ie(c.Va,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ca=b.trackingParams?g.Ys(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Ys(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Cd=b.icon.infoCardIconRenderer.trackingParams?
g.Ys(b.icon.infoCardIconRenderer.trackingParams):null,s2(a.player),a.Ut())},bFa=function(a,b,c,d,e){if(!a.player.T().jb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new iEa("openUrl","click",new gEa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.T(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.T(b.subscriberCountText))):(b.subscriberCountText&&(e=g.T(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.T(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.T(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.T(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R2(c,"branding","branding",f,d);l=REa(a);a.B.element.appendChild(l);f=new i3(l,p3(a),f);f.rq();g.D(f,f);a.K[c]=f}},VEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ma()||(d.unshift(b),b=g.Ra.apply(window,d),a.W.push(g.Xo(b)))}},cFa=function(a){return"annotation-editor"===a||"live-dashboard"===a},t2={},u2=null;g.Ta(w2,g.hn);g.k=w2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ia)this.progress=0,this.coords=this.u;else if(this.Jb())return!1;v2(this);this.startTime=a=g.A();-1==this.Ia&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.St();this.Eg("play");-1==this.Ia&&this.Eg("resume");this.Ia=1;var b=g.Qa(this);b in t2||(t2[b]=this);RDa();SDa(this,a);return!0};
g.k.stop=function(a){v2(this);this.Ia=0;a&&(this.progress=1);TDa(this,this.progress);this.Eg("stop");this.Tp()};
g.k.pause=function(){this.Jb()&&(v2(this),this.Ia=-1,this.Eg("pause"))};
g.k.ba=function(){0==this.Ia||this.stop(!1);this.Eg("destroy");w2.xd.ba.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.yw=function(){this.Eg("animate")};
g.k.Eg=function(a){this.dispatchEvent(new UDa(a,this))};
g.Ta(UDa,g.ql);g.Ta(x2,w2);x2.prototype.C=g.Ka;x2.prototype.yw=function(){this.C();x2.xd.yw.call(this)};
x2.prototype.Tp=function(){this.C();x2.xd.Tp.call(this)};
x2.prototype.St=function(){this.C();x2.xd.St.call(this)};
g.Ta(y2,x2);y2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(z2,g.C);z2.prototype.wa=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.Ho(a,b,c);this.u.push(a);return a};
z2.prototype.Ts=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.Ro(a,b,c);this.u.push(a);return a};
z2.prototype.Hb=function(a){g.Io(a);g.ob(this.u,a)};
z2.prototype.ba=function(){g.Io(this.u);this.u.length=0;g.C.prototype.ba.call(this)};g.u(D2,g.sS);g.k=D2.prototype;g.k.load=function(){g.sS.prototype.load.call(this);if(!E2(this)){var a=g.wH(this.player.getVideoData());a?(a=C2(a,WDa(this)),F2(this,a,!1)):XDa(this)}};
g.k.unload=function(){F2(this,null);this.C&&(this.C.abort(),this.C=null);g.sS.prototype.unload.call(this)};
g.k.pe=function(a,b){if(!E2(this))return null;if("loadCustomEndscreenRenderer"===a){var c=C2(b,"new");F2(this,c);return!0}return null};
g.k.getOptions=function(){return E2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ta=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<dFa.length;f++){var h=Math.abs(b.width-dFa[f]);if(-1===e||d>=h)e=f,d=h}d=eFa[e];this.B&&g.lg(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.u[f],
h=this.F[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ag(e.element,Math.round(h.width*a.width),f);g.tg(e.element,m,n);g.fn(e.element,fFa);m=h.left+h.width/2;h=h.top+l/2;g.H(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.fn(e.element,eFa);g.H(e.element,d);(e=g.ke(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.lg(e,"height",f+"px")}}}}};
g.k.dK=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())M2(this,this.endscreen.impressionUrls),(a=g.dt())&&this.endscreen.visualElement&&g.kt(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.u[a],c=this.F[a];g.H(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.H(b,"ytp-ce-shown");M2(this,c.impressionUrls);(b=g.dt())&&g.kt(b,c.visualElement,void 0);this.player.T().C&&this.player.xa("endscreenelementshown",
a)}};
g.k.eK=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.u[a];g.en(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.en(b,"ytp-ce-shown");this.player.T().C&&this.player.xa("endscreenelementhidden",a)}};
g.k.uP=function(a){var b=this;a.target===window&&(new g.F(function(){for(var c=g.q(Object.values(b.u)),d=c.next();!d.done;d=c.next())g.fn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var dFa=[346,426,470,506,570,640,853,1280,1920],eFa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),fFa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var hEa={nU:"current",GZ:"new"};var jEa={CLOSE:"close",RZ:"openUrl",lH:"subscribe"},kEa={sS:"click",CLOSE:"close",HV:"hidden",f0:"rollOut",g0:"rollOver",M0:"shown"};R2.prototype.Bd=function(){var a=mEa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var $Ea={OR:"anchored",QG:"branding",CHANNEL:"channel",mU:"cta",KV:"highlightText",JW:"label",PLAYLIST:"playlist",E_:"popup",V0:"speech",lH:"subscribe",t1:"title",VIDEO:"video",D2:"website"},ZEa={QG:"branding",hS:"card",BU:"drawer",JV:"highlight",gY:"marker",M_:"promotion",TEXT:"text",J2:"widget"};g.u(X2,g.C);g.k=X2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.ZD(a,b,{id:c});a.namespace="annotations_module";d&&this.va.set(a,d);e&&this.Ca.set(a,e);g.eN(this.context.J,[a])};
g.k.rq=function(){this.context.B.subscribe("resize",this.tr,this)};
g.k.Na=function(){return this.element};
g.k.zx=function(a,b,c,d,e,f){if(this.Ha)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ee(this.Na())};
g.k.tr=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P2(a);if(f){var h=rEa(f,a.target),l=function(){a.u&&e.context.J.pauseVideo();var m=e.context.videoData.jc||!1,n=g.Dp(f||"");m&&n&&(n.v||n.list)?g.pT(e.context.J.app,n.v,b,n.list,!1,void 0):g.TK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m3(this.context.logger,c,l,d);qEa(f)||(c=g.dt(),d=b.itct,c&&d&&g.ut(c,g.Ys(d)))}};
g.k.ba=function(){this.va.clear();this.Ca.clear();g.C.prototype.ba.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.u(b3,X2);g.k=b3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Bg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.tr=function(){var a=this.isAvailable();g.Cg(this.Na(),a);g.K(this.context.J.getRootNode(),g.WY.IV_DRAWER_ENABLED,a);s2(this.J)};
g.k.destroy=function(){var a=g.BT(g.rT(this.J));a&&a.tx(!1,void 0);try{this.J.getRootNode().removeChild(this.D)}catch(b){}g.so(this.W);g.Io(this.ka);this.la&&this.la.dispose();this.F&&this.F.dispose();X2.prototype.destroy.call(this)};
g.k.LH=function(){if(this.C){m3(this.context.logger,g3(this).Jf.close);var a=g.dt();a&&this.K&&g.ut(a,this.K);a3(this)}};
g.k.aI=function(){g.K(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.xJ=function(){var a=g.dt(),b=g3(this);b=b?b.Cd:this.Cd;a&&b&&g.rt(a,[b])};
g.k.wJ=function(){var a=g.dt(),b=g3(this);b=b?b.Cd:this.Cd;a&&b&&g.tt(a,[b])};
g.k.yK=function(){var a=g3(this);m3(this.context.logger,a.Jf.UF);var b=g.dt();b&&a&&g.rt(b,[a.Vg,a.Cd])};
g.k.zJ=function(){var a=g.dt(),b=g3(this);a&&b&&g.tt(a,[b.Vg])};
g.k.xK=function(a){var b=g3(this),c=g.dt();this.u?a?(a=this.context.logger,m3(a,b.Jf.Au),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Vg&&g.ut(c,b.Vg)):(a=this.context.logger,m3(a,b.Jf.Au),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Cd&&g.ut(c,b.Cd)):(a=this.context.logger,m3(a,b.Jf.Au),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Cd&&g.ut(c,this.Cd))};g.u(h3,X2);h3.prototype.rq=function(){X2.prototype.rq.call(this);FEa(this)};
h3.prototype.show=function(){X2.prototype.show.call(this);var a=g.dt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.rt(a,[g.Ys(b.itct)])};
h3.prototype.hide=function(){X2.prototype.hide.call(this);var a=g.dt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tt(a,[g.Ys(b.itct)])};g.u(i3,h3);
i3.prototype.show=function(){if(!this.isActive){h3.prototype.show.call(this);if(!this.K){g.H(this.Na(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({G:"img",ia:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Cg(this.B,!1);var b=this.createElement({G:"div",ia:["branding-img-container"]});b.appendChild(this.B);this.Na().appendChild(b);(b=this.annotation.Bd())&&Y2(this,this.B,b,this.annotation.id,a.session_data);
JEa(this,a);this.K=!0}g.Cg(this.Na(),!0);this.isActive=!0;this.B&&GEa(this,this.B)}};
i3.prototype.hide=function(){this.isActive&&(h3.prototype.hide.call(this),g.Cg(this.Na(),!1),this.isActive=!1)};
i3.prototype.destroy=function(){this.u&&(this.u.dispose(),this.u=null);h3.prototype.destroy.call(this)};g.u(j3,h3);g.k=j3.prototype;g.k.show=function(){this.isActive||(h3.prototype.show.call(this),this.P||(LEa(this),this.P=!0),g.Cg(this.Na(),!0),g.ym(function(){g.en(this.Na(),"iv-promo-inactive")},100,this),this.Na().removeAttribute("aria-hidden"),this.isActive=!0,l3(this),MEa(this),NEa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.H(this.Na(),"iv-promo-inactive"),this.isActive=!1,this.Na().setAttribute("aria-hidden","true"))};
g.k.zx=function(a,b,c,d,e,f){return this.isCollapsed?!1:h3.prototype.zx.call(this,a,b,c,d,e,f)};
g.k.QI=function(a){this.N=!0;k3(this,500,a)};
g.k.OI=function(){this.N=!1;OEa(this)};
g.k.II=function(a){a.stopPropagation();this.hide()};
g.k.JI=function(a){a.stopPropagation();l3(this);this.isCollapsed=!0;g.H(this.Na(),"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();h3.prototype.destroy.call(this)};g.u(n3,g.sS);g.k=n3.prototype;g.k.pe=function(a,b){if(!cFa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.f1(b);c&&o3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.u&&(wEa(this.u,b),s2(this.player)),!0}return null};
g.k.getOptions=function(){return cFa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ut=function(){if(this.D){var a=g.aF(this.player).getVideoContentRect(!0);g.Ag(this.D.element,a.width,a.height);g.tg(this.D.element,a.left,a.top)}if(this.u){var b=this.player.mi();a=this.u;b=b.width;g.K(a.D,"iv-drawer-small",426>=b);g.K(a.D,"iv-drawer-big",1280<=b)}};
g.k.wK=function(a){SEa(this,a.state);g.U(a.state,2)&&(this.Ep()&&this.NC()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.tx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Pp(h)&&h.responseXML?h.responseXML:null)&&(o3(b,h),g.H(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.sS.prototype.load.call(this);SEa(this,g.JI(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Zo()&&(a=VEa(this,a));var e={format:"XML",Rf:a,onError:function(){b.I=null},
Wh:{}};c.isPharma&&(e.Wh.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().K.get(d);f&&WEa(e,f);f=f&&(f.xr||f.Ho);if(!c.kr||f)c.Bg?TEa(this,c.Bg,e):(this.C=function(){b.Oa(e)},this.player.addEventListener("videodatachange",this.C));
g.iP(this.player,this.D.element,4);this.Ut();(f=g.xH(c))&&aFa(this,f);(f=g.yH(c))&&f.featuredChannel&&bFa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Oa=function(a){var b=this.player.getVideoData();b.Bg&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),TEa(this,b.Bg,a))};
g.k.unload=function(){g.GT(this.player,"annotations_module");for(var a=g.q(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.N=null;this.u&&(this.u.destroy(),this.u=null,s2(this.player));this.P=!1;this.I&&(this.I.abort(),this.I=null);this.K={};this.B.hide();g.sS.prototype.unload.call(this);this.D.detach();this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.k.DE=function(a){a===this.player.getVideoData().videoId&&(this.loaded?XEa(this):this.load())};
g.k.Ep=function(){return!!this.u&&this.u.isAvailable()};
g.k.NC=function(){this.Ep();return!!this.u&&this.u.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ep();this.u&&(a?c?$2(this.u,c,b):$2(this.u,"YOUTUBE_DRAWER_AUTO_OPEN",b):a3(this.u))};
g.k.tx=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ba=function(){this.player.T().K.unsubscribe("vast_info_card_add",this.DE,this);g.en(this.player.getRootNode(),g.WY.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.$o(a[b]);this.W.length=0;g.sS.prototype.ba.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.eU.annotations_module=n3;g.eU.creatorendscreen=D2;})(_yt_player);
